/**
 * All files in this package were generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
 * under XSDs specified by Recommended Chinese National Standard
 * <a href="http://www.dajs.gov.cn/module/download/downfile.jsp?classid=0&filename=88a7620d9d3f4e13b2baa52ab3487854.pdf">GB/T 33190-2016</a>.
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: 2021.03.31 at 11:17:16 AM CST
 */

@XmlSchema(
        namespace = "http://www.ofdspec.org/2016",
        elementFormDefault = XmlNsForm.QUALIFIED)
package org.ofdspec;

import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
